name: Node & AWS CLI

on:
  push:
    # paths:
    #   - cimg-node-awscli/variables.json
    #   - cimg-node-awscli/Dockerfile
    # branches:
    #   - master
    pull_request:
      branches:
        - master

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: get Node version from variables
        id: node-version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: './cimg-node-awscli/variables.json'
          prop_path: 'NODE_VERSION'
      - name: get Image Tag from variables
        id: TAG
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: './cimg-node-awscli/variables.json'
          prop_path: 'TAG'
      - name: login on DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build Docker Image
        working-directory: ./cimg-node-awscli
        run: docker build . --build-arg NODE_VERSION=$NODE_VERSION
        env:
          NODE_VERSION: ${{steps.node-version.outputs.prop}}
